language: scala

dist: xenial

addons:
  apt:
    packages:
    - wget 
    - make 
    - autoconf 
    - g++ 
    - flex 
    - bison

install:
  - ./travis/install_verilator.sh
  # next line check for verilator is actually installed and available
  - verilator -V 

cache:
  directories:
  - /usr/local/share/verilator
  - /verilator
   
script:
  - sbt 'testOnly dontcouple.mTester'

jdk:
  - oraclejdk8
  - openjdk8
  
scala:
  - 2.11.12
  - 2.12.4
